sass:
    sass_dir: css

collections:
    posts:
        permalink: /blog/:categories/:year-:month-:day-:title:output_ext

plugins:
 - jekyll-sitemap
 - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"
